name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Debug - List workspace before build
        run: ls -la
      - name: Build with Next.js
        run: npm run build
      - name: Debug - List workspace after build
        run: ls -la
      - name: Create .nojekyll file
        run: touch out/.nojekyll || echo "Failed to create .nojekyll file"
      - name: List output directory
        run: ls -la out || echo "out directory does not exist"
      - name: Upload artifact (standard)
        uses: actions/upload-artifact@v4
        with:
          name: github-pages-debug
          path: ./out
      - name: Create artifact directory
        run: |
          mkdir -p ./_site
          cp -r ./out/* ./_site/ || echo "Failed to copy files"
      - name: List _site directory
        run: ls -la _site || echo "_site directory does not exist"
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3 